# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EE-x | Cross-platform library for cocos2d-x
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.19.2
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site
# Some configuration settings cannot be changed for GitHub Pages sites.
lsi: false
safe: true
source: . # [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

baseurl: /ee-x

exclude:
  - proj.android_studio
  - proj.ios_mac
  - res
  - test
  - third_party

# minimal-mistakes theme settings.
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/
# https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
minimal_mistakes_skin: dirt
repository: "Senspark/ee-x"
footer:
  links:
    - label: "Google Play"
      icon: "fab fa-google-play"
      url: "https://play.google.com/store/apps/dev?id=7830868662152106484"
    - label: "App Store"
      icon: "fab fa-app-store-ios"
      url: "https://apps.apple.com/us/developer/id560842775"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://www.facebook.com/TeamSenspark"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Senspark"

# Front matters config.
defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
          nav: docs