LOCAL_PATH := $(call my-dir)

$(call import-add-path, $(LOCAL_PATH))

$(call import-module, src/cpp/ee)
$(call import-module, src/cpp/ee/firebase_analytics)
$(call import-module, src/cpp/ee/firebase_core)
$(call import-module, src/cpp/ee/firebase_dynamic_link)
$(call import-module, src/cpp/ee/firebase_messaging)
$(call import-module, src/cpp/ee/firebase_remote_config)
$(call import-module, src/cpp/ee/firebase_storage)
# $(call import-module, src/ee/jsb/admob)
# $(call import-module, src/ee/jsb/ads)
# $(call import-module, src/ee/jsb/apps_flyer)
# $(call import-module, src/ee/jsb/core)
# $(call import-module, src/ee/jsb/crashlytics)
# $(call import-module, src/ee/jsb/facebook)
# $(call import-module, src/ee/jsb/facebook_ads)
# $(call import-module, src/ee/jsb/firebase/analytics)
# $(call import-module, src/ee/jsb/firebase/performance)
# $(call import-module, src/ee/jsb/firebase/remote_config)
# $(call import-module, src/ee/jsb/google)
# $(call import-module, src/ee/jsb/iron_source)
# $(call import-module, src/ee/jsb/notification)
# $(call import-module, src/ee/jsb/recorder)
# $(call import-module, src/ee/jsb/soomla)
# $(call import-module, src/ee/jsb/unity_ads)
# $(call import-module, src/ee/jsb/vungle)
$(call import-module, third_party/firebase_cpp_sdk)
$(call import-module, third_party/jansson)
$(call import-module, third_party/soomla/core)
$(call import-module, third_party/soomla/store)
