# Project information
site_name: EE-x | Cross-platform library for Cocos2d-x / Unity
site_author: enrevol
site_url: https://senspark.com

# Repository
repo_name: Senspark/ee-x
repo_url: https://github.com/Senspark/ee-x

# Copyright
copyright: Copyright &copy; 2017 - 2020 Senspark

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs

nav:
  - Home:
    - index.md
    - contributions.md
  - Cocos2d-x:
    - cocos2dx/getting-started.md
    - cocos2dx/design-patterns.md
    - cocos2dx/utils.md
    - cocos2dx/multi-ad.md
    - cocos2dx/firebase-analytics.md
    - cocos2dx/firebase-crashlytics.md
    # - cocos2dx/firebase-dynamic-link.md
    # - cocos2dx/firebase-messaging.md
    - cocos2dx/firebase-performance.md
    - cocos2dx/firebase-remote-config.md
    # - cocos2dx/firebase-storage.md
    - cocos2dx/ad-mob.md 
    - cocos2dx/app-lovin.md
    - cocos2dx/facebook-ads.md
    - cocos2dx/iron-source.md
    - cocos2dx/unity-ads.md
    - cocos2dx/vungle.md
    - cocos2dx/adjust.md
    - cocos2dx/apps-flyer.md
    - cocos2dx/facebook.md
    - cocos2dx/notification.md
    - cocos2dx/play.md
    - cocos2dx/soomla-store.md
    - cocos2dx/store.md
  - Cocos Creator:
    - cocosjs/getting-started.md
    - cocosjs/multi-ad.md
    - cocosjs/adjust.md
    - cocosjs/facebook.md
  - Unity:
    - unity/getting-started.md
    - unity/design-patterns.md
    - unity/utils.md
    - unity/multi-ad.md
    - unity/ad-mob.md
    - unity/adjust.md
  - Contributions:
    - contributions/update-documents.md
    - contributions/add-more-features.md

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Senspark
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/TeamSenspark
    - icon: fontawesome/brands/google-play
      link: https://play.google.com/store/apps/dev?id=7830868662152106484
    - icon: fontawesome/brands/app-store-ios
      link: https://apps.apple.com/us/developer/id560842775

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - minify:
      minify_html: true
      minify_js: true