ee_x_path = 'https://github.com/Senspark/ee-x'

target 'ee_x_test_mobile' do
    pod 'ee-x/crashlytics',     :git => ee_x_path
    pod 'ee-x/notification',    :git => ee_x_path
    pod 'ee-x/firebase',        :git => ee_x_path
    pod 'ee-x/facebook-ads',    :git => ee_x_path
    pod 'ee-x/applovin'         :git => ee_x_path
    pod 'ee-x/ironsource',      :git => ee_x_path
    pod 'ee-x/unity-ads',       :git => ee_x_path
    pod 'ee-x/vungle',          :git => ee_x_path

    pod 'cocos2d-x', :git => 'https://github.com/Senspark/cocos2d-x-3.15'
end

target 'ee_x_test_desktop' do
    pod 'ee-x/crashlytics',     :git => ee_x_path
    pod 'ee-x/firebase',        :git => ee_x_path
end
