def pod_ee_x(name)
    full_name = 'ee-x/' + name
    pod full_name, :path => '../../'
    # pod full_name, :git => 'https://github.com/Senspark/ee-x'
end

abstract_target 'common' do
    pod 'cocos2d-x', :git => 'https://github.com/Senspark/cocos2d-x-lite'
    
    target 'ee_x_test_mobile' do
        pod_ee_x('admob')
        pod_ee_x('appsflyer')
        pod_ee_x('crashlytics')
        pod_ee_x('facebook')
        pod_ee_x('firebase-analytics')
        pod_ee_x('firebase-dynamic-link')
        pod_ee_x('firebase-messaging')
        pod_ee_x('firebase-remote-config')
        pod_ee_x('firebase-storage')
        pod_ee_x('google-analytics')
        pod_ee_x('notification')
        pod_ee_x('recorder')
        
        pod_ee_x('applovin')
        pod_ee_x('facebook-ads')
        pod_ee_x('ironsource')
        pod_ee_x('unity-ads')
        pod_ee_x('vungle')
        pod_ee_x('game-center')
        
        # pod_ee_x('applovin-mediation')
        # pod_ee_x('facebook-ads-mediation')
        # pod_ee_x('ironsource-mediation')
        # pod_ee_x('unity-ads-mediation')
        # pod_ee_x('vungle-mediation')
    end

    target 'ee_x_test_desktop' do
        pod_ee_x('ads')
        pod_ee_x('crashlytics')
        pod_ee_x('firebase-analytics')
        pod_ee_x('firebase-dynamic-link')
        pod_ee_x('firebase-messaging')
        pod_ee_x('firebase-remote-config')
        pod_ee_x('firebase-storage')
    end
end
