def pod_ee_x(name)
    full_name = 'ee-x/' + name
    pod full_name, :path => '../../'
    # pod full_name, :git => 'https://github.com/Senspark/ee-x'
end

abstract_target 'common' do
    pod_ee_x('cocos')
    pod_ee_x('soomla-store')
    
    target 'ee_x_test_mobile' do
        platform :ios, '12.0'
        
        pod_ee_x('cpp')
        pod_ee_x('ios-ad-colony')
        pod_ee_x('ios-ad-mob')
        pod_ee_x('ios-adjust')
        pod_ee_x('ios-app-lovin')
        pod_ee_x('ios-apps-flyer')
        pod_ee_x('ios-facebook')
        pod_ee_x('ios-facebook-ads')
        pod_ee_x('ios-firebase-crashlytics')
        pod_ee_x('ios-firebase-performance')
        pod_ee_x('ios-iron-source')
        pod_ee_x('ios-notification')
        pod_ee_x('ios-play')
        pod_ee_x('ios-recorder')
        pod_ee_x('ios-store')
        pod_ee_x('ios-unity-ads')
        pod_ee_x('ios-vungle')
        pod_ee_x('firebase-dynamic-link')
        pod_ee_x('firebase-messaging')
        pod_ee_x('firebase-remote-config')
        pod_ee_x('firebase-storage')
        
        pod 'Adjust', :modular_headers => true
    end

    target 'ee_x_test_desktop' do
        platform :osx, '10.14'
    end
end
