abstract_target 'common' do
    abstract_target 'crashlytics' do
        pod 'Fabric'
        pod 'Crashlytics'
        
        target 'ee_x_mobile_crashlytics'
        target 'ee_x_desktop_crashlytics'
    end
    
    target 'ee_x_mobile_firebase' do
        pod 'Firebase/Core'
        pod 'Firebase/RemoteConfig'
        pod 'Firebase/Storage'
    end

    target 'ee_x_mobile_facebook_ads' do
        pod 'FBAudienceNetwork'
    end

    target 'ee_x_mobile_unity_ads' do
        pod 'UnityAds'
    end
    
    target 'ee_x_mobile_iron_source' do
        pod 'IronSourceSDK'
    end
    
    target 'ee_x_mobile_app_lovin' do
        pod 'AppLovinSDK'
    end
    
    target 'ee_x_mobile_vungle' do
        pod 'VungleSDK-iOS', '4.1.0'
    end
    
    target 'ee_x_mobile_admob' do
        pod 'Google-Mobile-Ads-SDK'
    end
end
