abstract_target 'common' do
    abstract_target 'crashlytics' do
        pod 'Fabric'
        pod 'Crashlytics'        
        
        target 'ee_x_mobile_crashlytics'
        target 'ee_x_desktop_crashlytics'
    end
end
