abstract_target 'common' do
    abstract_target 'crashlytics' do
        pod 'Fabric'
        pod 'Crashlytics'
        
        target 'ee_x_mobile_crashlytics'
        target 'ee_x_desktop_crashlytics'
    end
    
    target 'ee_x_mobile_firebase' do
        pod 'Firebase/Core'
        pod 'Firebase/RemoteConfig'
        pod 'Firebase/Storage'
    end

    target 'ee_x_mobile_facebook_ads' do
        pod 'FBAudienceNetwork'
    end
end
